// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaDkN6B7IDfeRnTeqw8965MAMomD-T8jc',
    appId: '1:59440754784:web:cd9534113cf385b8f65305',
    messagingSenderId: '59440754784',
    projectId: 'campus-74cdc',
    authDomain: 'campus-74cdc.firebaseapp.com',
    storageBucket: 'campus-74cdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftbiDo5q9YuoE0LsSMZ6CFK-_no96LnE',
    appId: '1:59440754784:android:5edb351bb323e666f65305',
    messagingSenderId: '59440754784',
    projectId: 'campus-74cdc',
    storageBucket: 'campus-74cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1SdLR1eDEZuW776-RGVSnd34GQg43YE',
    appId: '1:59440754784:ios:d57ebb02b7f62df8f65305',
    messagingSenderId: '59440754784',
    projectId: 'campus-74cdc',
    storageBucket: 'campus-74cdc.firebasestorage.app',
    iosBundleId: 'com.example.hub',
  );
}
